routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});
Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::resource('doctors', 'Admin\DoctorController');
    Route::post('doctors/suspend', 'Admin\DoctorController@suspend')->name('doctors.suspend');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','Admin\UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','Admin\UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','Admin\UsersController@suspendUser')->name('user.suspendUser');
    Route::post('deleteUser','Admin\UsersController@delete')->name('user.delete');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'Admin\SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/terms/doctors', 'Admin\SettingsController@terms_doctors')->name('settings.terms.doctors');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'Admin\SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');


    Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'Admin\CitiesController');
    Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');


    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');



    Route::resource('questions', 'Admin\QuestionController');
    Route::post('questions/delete', 'Admin\QuestionController@delete')->name('questions.delete');


    Route::resource('reports', 'Admin\ReportsController');
    Route::get('reports-supervisor/{id}', 'Admin\ReportsController@supervisor')->name('reports-supervisor');


    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'Admin\BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'Admin\BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'Admin\BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'Admin\ContactUsController');
    Route::get('updateIsRead', 'Admin\ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'Admin\ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'Admin\ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'Admin\BankProjectsController');
    Route::post('BankProjects/accepted', 'Admin\BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'Admin\BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'Admin\ReportsController');
    Route::get('provider_data_report', 'Admin\ReportsController@gym_data')->name('provider_data_report');


    Route::get('public/notifications', 'Admin\NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'Admin\NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::post('send/public/notifications', 'Admin\NotificationsController@sendPublicNotifications')->name('send.public.notifications');
    Route::post('notifications/delete', 'Admin\NotificationsController@delete')->name('notification.delete');



    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');




Route::get('/activation_code',function (\Illuminate\Http\Request $request){

    if ($request->phone){
        $code = \App\Models\VerifyUser::wherePhone($request->phone)->first();

        if ($code){
            return $code->action_code;
        }
        return 'أتاكدي من التليفون ';
    }


    return 'مدخلي الكود ياانسة الله الله';
});

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Helpers\Images;
use App\Http\Requests\Admin\Update_User_vaild;
use App\Libraries\PushNotification;
use App\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use UploadImage;
use Validator;

class UsersController extends Controller
{


    public $public_path;
    public $domain;
    public $push;

    public function __construct(PushNotification $push)
    {
        $this->public_path = 'files/';
        $this->domain = URL('/').'/';
        $this->push = $push;
    }

    public function index(Request $request)
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        $query = User::where('defined_user','user')->where('is_active', 1);

        $pageName = 'إدارة المستخدمين';

        $users =  $query->latest()->get();

        return view('admin.users.index', compact('users' , 'pageName'));
    }

    public function edit($id){
        $user = User::findOrFail($id);

        return view('admin.users.edit',compact('user'));
    }

    public function create()
    {
        return view('admin.users.add', compact('cities'));
    }

    public function show($id)
    {
        $user = User::where('defined_user','user')->with('children.questions')->findOrFail($id);

        return view('admin.users.show', compact('user'));
    }

    public function accpetedUser(Request $request){

        $user = User::with('devices')->findOrFail($request->id);
        $devices = $user['devices']->pluck('device');
        if ($user){

            $user->update(['is_accepted' => 1]);

            $this->push->sendPushNotification($devices,null,'  الإدارة',  ' تم قبول طلبك من الإدارة '  ,[
                'type' =>  'refresh_token'
            ]);

            return response()->json( [
                'status' => true ,
            ] , 200 );

        }else{

            return response()->json( [
                'status' => false
            ] , 200 );

        }

    }



    public function refuseUser(Request $request){
        $user = User::with('devices')->findOrFail($request->id);
        $devices = $user['devices']->pluck('device');

        $user->update(['is_accepted' => -1,'message' => $request->message]);
        $this->push->sendPushNotification($devices,null,'  الإدارة',  'للأسف.. تم رفض  طلبك من الإدارة '  ,[
            'type' =>  'refresh_token'
        ]);

        session()->flash('success', 'لقد تم  الرفض   بنجاح.');
        return redirect()->back();
    }

    public function update(Update_User_vaild $request, $id){
        $user = User::find($id);
        $user->fill($request->validated());
        if ($request->hasFile('image')):
            $user->image =  $this->public_path   .Images::uploadImage($request,'image',$this->public_path);
        endif;
        $user->save();

        session()->flash('success', 'لقد تم تعديل البيانات  بنجاح.');
        return redirect()->route('users.index');
    }



    public function reAcceptUser(Request $request){
        $user = User::findOrFail($request->id);

        $user->update([  'is_accepted' => 1,'message' => null]);


        return response()->json( [
            'status' => true ,
        ] , 200 );
    }


    public function suspendUser(Request $request)
    {
        $model = User::with('devices','orders','doctor_orders')->findOrFail($request->id);

        $orders = $model['orders']->whereIn('status',['pending','accepted']);
        $doctor_orders = $model['doctor_orders']->whereIn('status',['pending','accepted']);

        if (count($orders) > 0 || count($doctor_orders) > 0 ){
            session()->flash('myErrors',"للأسف ...لا يمكن حظر الأن لان لديه طلبات حالية او جارية");
            return redirect()->back();
        }
        $devices = $model['devices']->pluck('device');

        $model->is_suspend = $request->type;
        $model->message = $request->message;
        if ($request->type == -1) {
            if ($devices){
                collect($model['devices'])->each->delete();
            }
            $this->push->sendPushNotification($devices,null,'حظر الإدارة',  ' تم حظرك من الإدارة بسبب ' . $request->message ,[
                'type' =>  'logout'
            ]);
            $model->is_suspend = 1;
//            $model->api_token = Str::random(60);
            $message = "لقد تم حظر  بنجاح";

        } else {

            $model->message = null;
            $message = "لقد تم فك الحظر بنجاح";
        }

        if ($model->save()) {
            session()->flash('success',$message);
            return redirect()->back();
        }

    }




    public function delete(Request $request)
    {
        $model = User::findOrFail($request->id);

        if ($model->delete()) {
            return response()->json([
                'status' => true,
                'data' => $model->id
            ]);
        }
    }

}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Doctor\DoctorResource;
use App\Http\Resources\User\UserResource;
use App\Models\Notification;
use App\Models\Order;
use App\Traits\paginationTrait;
use App\Traits\RespondsWithHttpStatus;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    use  RespondsWithHttpStatus , paginationTrait;
    public  $lang;
    public  $path;
    public function __construct( )
    {
        $this->lang = request()->headers->get('Accept-Language') ?  : 'ar';

        app()->setLocale($this->lang);

        $this->path = 'files/';

        $this->middleware('auth:api')->only([ 'payment_doctor','test_payment' ]);
    }


    public function show($id){
        $user = User::where('defined_user','!=','admin')->findOrFail($id);

        if ($user->defined_user == 'doctor'){

            $data = new DoctorResource($user);
        }else{

            $data = new UserResource($user);
        }
        return $this->success('تفاصيل المستخدم', $data);
    }

    public function payment_doctor(){
        $user = Auth::user();


        if ($user === "user"){
            return $this->failure('لا يوجد حساب او رصيد لك');
        }

        $orders = Order::whereDoctorId($user->id)
            ->where('status','finish')
            ->select(DB::raw('sum(Case When app_percentage IS NULL Then price Else price - (price * app_percentage / 100 )  End ) as doctor,
                        sum(Case When app_percentage IS NULL Then "0" Else  price * app_percentage / 100   End ) as admin
                '))
            ->first();


        return  $this->success('العمولة', $orders);
    }

    function test_payment(){
        $user = Auth::user();


        $orders = Order::whereDoctorId($user->id)
            ->where('status','finish')
            ->select(DB::raw('sum(Case When app_percentage IS NULL Then price Else price - (price * app_percentage / 100 )  End ) as doctor,
                        sum(Case When app_percentage IS NULL Then "0" Else  price * app_percentage / 100   End ) as admin
                '))
            ->first();

        return $orders;
    }

}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))



@section('styles')


    <style>
        #parsley-id-multiple-roles li{
            position: absolute;
            top: -22px;
            right: 80px;
        }
    </style>

@endsection

@section('content')


    <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}



    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12 col-sm-offset-2" >
                <div class="btn-group pull-right m-t-15">
                   {{--  <a href="{{ route('users.create') }}" type="button" class="btn btn-custom waves-effect waves-light"
                       aria-expanded="false"> @lang('maincp.add')
                        <span class="m-l-5">
                        <i class="fa fa-plus"></i>
                    </span>
                    </a> --}}
                </div>
                <h4 class="page-title">@lang('maincp.edit_user_data')</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-8 " >
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">@lang('maincp.edit_data')</h4>

<div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="userName">@lang('maincp.full_name')*</label>
                            <input type="text" name="name" value="{{ $user->name   }}" class="form-control"
                                   required
                                   placeholder="@lang('maincp.full_name')..."
                                   data-parsley-trigger="keyup"
                                   data-parsley-required-message="اسم المستخدم بالكامل مطلوب"
                                   data-parsley-maxlength="55"
                                   data-parsley-pattern="^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]+$"
                                   data-parsley-pattern-message="النظام لا يقبل العلامات الخاصة"
                                   data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (55) حرف"
                                   />
                            <p class="help-block" id="error_userName"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>

                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="userPhone">@lang('maincp.mobile_number') *</label>
                            <input type="text" name="phone" value="{{ $user->phone   }}"
                                   class="form-control numbersOnly  phone" required
                                   placeholder="@lang('maincp.mobile_number') ..."/>
                            @if($errors->has('phone'))
                                <p class="help-block">
                                    {{ $errors->first('phone') }}
                                </p>
                            @endif
                        </div>
                    </div>


                      </div>


                    <div class="col-xs-12">
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="emailAddress">@lang('maincp.e_mail') *</label>

                            <input type="email" name="email" data-parsley-trigger="keyup"
                                   value="{{ $user->email   }}"
                                   class="form-control email" placeholder="@lang('maincp.e_mail')..." required/>
                            @if($errors->has('email'))
                                <p class="help-block">{{ $errors->first('email') }}</p>
                            @endif

                        </div>

                    </div>

                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="pass1">@lang('maincp.password')*</label>


                            <input type="password" name="password" id="pass1"
                                   class="form-control"
                                   placeholder="@lang('maincp.password')..."
                                   data-parsley-trigger="keyup"
                                   data-parsley-required-message="كلمة المرور مطلوبة"
                                   data-parsley-maxlength="55"
                                   data-parsley-minlength="6"
                                   data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (55) حرف"
                                   data-parsley-minlength-message=" أقل عدد الحروف المسموح بها هى (6) حرف"

                            />

                            @if($errors->has('password'))
                                <p class="help-block">{{ $errors->first('password') }}</p>
                            @endif

                        </div>
                    </div>


                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="passWord2">@lang('maincp.confirm_password')*</label>
                            <input data-parsley-equalto="#pass1" name="password_confirmation" type="password"
                                   placeholder="@lang('maincp.confirm_password').."
                                    data-parsley-trigger="keyup"
                                   data-parsley-required-message="تأكيد كلمة المرور مطلوب"
                                   data-parsley-equalto-message="تأكيد كلمة المرور غير متطابقة"

                                   class="form-control">
                            @if($errors->has('password_confirmation'))
                                <p class="help-block">{{ $errors->first('password_confirmation') }}</p>
                            @endif


                        </div>
                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                           @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->

            <div class ="col-sm4">

                <div class="card-box" style="overflow: hidden;">
                <h4 class="header-title m-t-0 m-b-30">@lang('institutioncp.personal_image')</h4>
                    <div class="form-group">
                        <div class="col-sm-12">

                            <input type="hidden" value="{{ $user->image }}" name="oldImage"/>
                            <input type="file" name="image" class="dropify" data-max-file-size="6M"
                                        data-default-file="{{ $helper->getDefaultImage( $user->image ? URL('/').'/' . $user->image : null , request()->root().'/default.png') }}"/>

                        </div>
                    </div>
                </div>

            </div>

        </div>
        <!-- end row -->
    </form>

@endsection

@section('scripts')

<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

@endsection

resources/views/admin/users/profile.blade.php
@extends('admin.layouts.master')
@section('title',__('maincp.personal_page'))
@section('content')




    {{--<div class="row">--}}
    {{--<div class="col-xs-6 col-md-4 col-sm-4">--}}
    {{--<h3 class="page-title">@lang('maincp.personal_page')</h3>--}}
    {{--</div>--}}

    {{--<div class="m-t-15 col-xs-6 col-md-8 col-sm-8 text-right">--}}
    {{--<a href="{{ route('users.edit', auth()->id()) }}">--}}
    {{--<button type="button" class="btn btn-success">@lang('maincp.edit_data')</button>--}}


    {{--<button type="button" class="btn btn-custom  waves-effect waves-light"--}}
    {{--onclick="window.history.back();return false;">@lang('maincp.back')<span class="m-l-5"><i--}}
    {{--class="fa fa-reply"></i></span>--}}
    {{--</button>--}}
    {{--</a>--}}
    {{--</div>--}}
    {{--</div>--}}


    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="btn-group pull-right m-t-15">
                <a href="{{ route('users.edit', auth()->id()) }}">
                    <button type="button" class="btn btn-success">@lang('maincp.edit_data')</button>


                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;">@lang('maincp.back')<span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </a>
            </div>
            <h4 class="page-title">@lang('maincp.personal_page')</h4>
        </div>
    </div>




    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="bg-picture card-box">
                <div class="profile-info-name">
                    <div class="profile-info-detail">
                        <h4 class="m-t-0 m-b-0">@lang('maincp.personal_data')</h4>

                        {{--<div class="m-t-20 text-center">--}}

                        {{--<a data-fancybox="gallery"--}}
                        {{--href="{{ $helper->getDefaultImage($user->image, request()->root().'/assets/admin/custom/images/default.png') }}">--}}
                        {{--<img class="img-thumbnail"--}}
                        {{--src="{{ $helper->getDefaultImage($user->image, request()->root().'/assets/admin/custom/images/default.png') }}"/>--}}
                        {{--</a>--}}

                        {{--</div>--}}

                        <div class="panel-body">

                            <div class="col-lg-4 col-xs-12">
                                <label>@lang('maincp.full_name') :</label>
                                <p>{{ $user->name or $user->username }}</p>
                            </div>

                            <div class="col-lg-4 col-xs-12">
                                <label>@lang('maincp.mobile_number') :</label>
                                <p>{{ $user->phone }}</p>
                            </div>

                            <div class="col-lg-4 col-xs-12">
                                <label>@lang('maincp.e_mail') :</label>
                                <p>{{ $user->email }}</p>
                            </div>

                            <div class="col-lg-12 col-xs-12">
                                <label>@lang('maincp.roles')</label>


                                <ul class="m-t-20">
                                    @foreach($user->roles as $role)
                                        <li>{{ $role->title }}</li>
                                    @endforeach
                                </ul>

                            </div>


                            {{--<div class="col-lg-3 col-xs-12">--}}
                            {{--<label>@lang('maincp.address'):</label>--}}
                            {{--<p>{{ $user->address }}</p>--}}
                            {{--</div>--}}
                            {{----}}


                        </div>
                    </div>
                    <!-- end card-box-->
                </div>
            </div>
        </div>
        <!--/ meta -->
    </div>

@endsection