routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});
Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::resource('doctors', 'Admin\DoctorController');
    Route::post('doctors/suspend', 'Admin\DoctorController@suspend')->name('doctors.suspend');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','Admin\UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','Admin\UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','Admin\UsersController@suspendUser')->name('user.suspendUser');
    Route::post('deleteUser','Admin\UsersController@delete')->name('user.delete');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'Admin\SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/terms/doctors', 'Admin\SettingsController@terms_doctors')->name('settings.terms.doctors');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'Admin\SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');


    Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'Admin\CitiesController');
    Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');


    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');



    Route::resource('questions', 'Admin\QuestionController');
    Route::post('questions/delete', 'Admin\QuestionController@delete')->name('questions.delete');


    Route::resource('reports', 'Admin\ReportsController');
    Route::get('reports-supervisor/{id}', 'Admin\ReportsController@supervisor')->name('reports-supervisor');


    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'Admin\BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'Admin\BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'Admin\BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'Admin\ContactUsController');
    Route::get('updateIsRead', 'Admin\ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'Admin\ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'Admin\ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'Admin\BankProjectsController');
    Route::post('BankProjects/accepted', 'Admin\BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'Admin\BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'Admin\ReportsController');
    Route::get('provider_data_report', 'Admin\ReportsController@gym_data')->name('provider_data_report');


    Route::get('public/notifications', 'Admin\NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'Admin\NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::post('send/public/notifications', 'Admin\NotificationsController@sendPublicNotifications')->name('send.public.notifications');
    Route::post('notifications/delete', 'Admin\NotificationsController@delete')->name('notification.delete');



    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');




Route::get('/activation_code',function (\Illuminate\Http\Request $request){

    if ($request->phone){
        $code = \App\Models\VerifyUser::wherePhone($request->phone)->first();

        if ($code){
            return $code->action_code;
        }
        return 'أتاكدي من التليفون ';
    }


    return 'مدخلي الكود ياانسة الله الله';
});

app/Models/Category.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{


    public function doctors(){
        return $this->belongsToMany(User::class,'category_doctor','user_id','category_id');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Validator;
use UploadImage;


class CategoriesController extends Controller
{

    public $public_path;

    public function __construct()
    {
        $this->public_path = 'files/categories/';
    }

    public function index(Request $request)
    {
        $categories = Category::latest()->get();

        $pageName = 'إدارة  التخصصات';

        return view('admin.categories.index',compact('categories','pageName'));
    }
    public function create()
    {
	    $pageName = '   اسم  التخصص';

        return view('admin.categories.create')->with(compact('pageName'));
    }

    public function store(Request $request)
    {
        $category = new Category;
        $category->name_ar = $request->name_ar;
        $category->name_en = $request->name_en;

        if ($request->hasFile('image')):
            $category->image = '/public/' .  $this->public_path . UploadImage::uploadImage($request, 'image', $this->public_path);
        endif;

        if ($category->save()) {

            $url =  route('categories.index');
            $name = ' التخصص  ';

            return response()->json([
                'status' => true,
                "message" => __('trans.addingSuccess',['itemName' => $name]),
                "url" => $url,

            ]);

        }

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $pageName = '         التخصص';

        return view('admin.categories.edit')->with(compact('category', 'pageName' ));
    }


    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name_ar = $request->name_ar;
        $category->name_en = $request->name_en;

        if ($request->hasFile('image')):
            $category->image =  '/public/' .  $this->public_path . UploadImage::uploadImage($request, 'image', $this->public_path);
        endif;

        if ($category->save()) {

            $url =  route('categories.index');
            $name = '   التخصص';

            return response()->json([
                'status' => true,
                "message" => __('trans.editSuccess',['itemName' => $name]),
                "url" => $url,
            ]);
        }

    }



       public function delete(Request $request){
	    if (!Gate::allows('settings_manage')) {
		 return abort(401);
	    }

	    $model = Category::with('doctors')->findOrFail($request->id);

	    if (count($model['doctors']) > 0) {

		 return response()->json([
		         'status' => false,
		         'message' => "عفواً, لا يمكنك حذف التخصص نظراً لوجود اخصائين  بها"
		 ]);
	    }


	    if ($model->delete()) {
             return response()->json([
                     'status' => true,
                     'data' => $model->id
             ]);
	    }

       }

       public function suspend(Request $request)
       {
	    $model = Category::findOrFail($request->id);
	    $model->is_suspend = $request->type;
	    if ($request->type == 1) {

            $message = "لقد تم حظر التخصص بنجاح";
	    } else {
            $message = "لقد تم فك الحظر على التخصص بنجاح";
	    }
//	    if (count($model->users) > 0) {
//		 return response()->json([
//		         'status' => false,
//		         'message' => 'عفواً, لا يمكنك حظر القسم نظراً لوجود مستخدمين مشتركين فيها'
//		 ]);
//	    }
//
//	    if (count($model->product) > 0) {
//
//		 return response()->json([
//		         'status' => false,
//		         'message' => "عفواً, لا يمكنك حذف القسم نظراً لوجود منتجات  فيها"
//		 ]);
//	    }

	    if ($model->save()) {
		 return response()->json([
		         'status' => true,
		         'message' => $message,
		         'id' => $request->id,
		         'type' => $request->type

		 ]);
	    }

       }



}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')



    <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">




                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                <input type="text" name="name_ar"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                <input type="text" name="name_en"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_en'))
                                    <p class="help-block">
                                        {{ $errors->first('name_en') }}
                                    </p>
                                @endif
                            </div>
                        </div>

{{--                        <div class="col-xs-6">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="usernames">صورة التخصص  *</label>--}}
{{--                                <input type="file" name="image" class="dropify" data-max-file-size="6M"/>--}}
{{--                            </div>--}}

{{--                        </div>--}}



                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" id="my_submit_button" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')
    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        function validImages() {

            var images = $( "input[name='image']" ).val();


            if ( images === undefined || images == ""   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                var $toast = toastr[shortCutFunction](msg, title);
                $toastlast = $toast;
                return false;
            }

            return true;
        }


        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            // if (form.parsley().isValid() && validImages()){
            if (form.parsley().isValid() ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    beforeSend: function() {
                        $("#my_submit_button").hide();
                    },
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 1500);
                    },
                    error: function (data) {
                        $("#my_submit_button").show();
                    }
                });
            }else {
                $('.loading').hide();
            }
        });

    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')


    <form method="POST" action="{{ route('categories.update', $category->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}


    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إسم {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">تعديل {{$pageName}}</h4>

                    <div class="row">

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                    <input type="text" name="name_ar"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required value="{{ $category->name_ar }}"
                                           placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_ar'))
                                        <p class="help-block">
                                            {{ $errors->first('name_ar') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                    <input type="text" name="name_en" value="{{$category->name_en}}"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required
                                           placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_en'))
                                        <p class="help-block">
                                            {{ $errors->first('name_en') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

{{--                            <div class="col-xs-4">--}}


{{--                                <div class="form-group">--}}
{{--                                    <label for="usernames">صورة التخصص *</label>--}}


{{--                                    <input type="hidden" value="{{ $category->image }}" name="oldImage"/>--}}
{{--                                    <input type="file" name="image" class="dropify" data-max-file-size="6M"--}}
{{--                                           data-default-file="{{ request()->root().$category->image }}"/>--}}


{{--                                </div>--}}


{{--                            </div>--}}


                        <!-- end col -->
                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" id="my_submit_button" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

    <script type="text/javascript">
        function validImages() {

            var images = $( "input[name='oldImage']" ).val();


            if ( images === undefined || images == ""   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                var $toast = toastr[shortCutFunction](msg, title);
                $toastlast = $toast;
                return false;
            }

            return true;
        }

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);

            form.parsley().validate();

            // if (form.parsley().isValid() && validImages()){
            if (form.parsley().isValid() ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    beforeSend: function() {
                        $("#my_submit_button").hide();
                    },
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();

                        // $('form').trigger("reset");

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 1500);
                    },
                    error: function (data) {
                        $("#my_submit_button").show();
                    }
                });

            }


        });

    </script>
@endsection